### ISSUE TITLE
porting to new garden structure + putting on PyPi

### ISSUE THREAD

**Issue by goffi-contrib** [kivy-garden/garden.modernmenu#7]
Hello,

I there still somebody maintaining this widget? I would like to port it to new garden structure and put it on PyPi, but I'm not the original author or maintainer so I'm asking here first.

Thanks!

**Comment by AndreMiras** [comment]
We just created https://github.com/kivy-garden/modernmenu using the template and added you to the collaborators.
You can follow this guide to port it https://kivy-garden.github.io/#guideformigratingflowersfromlegacystructure

**Comment by goffi-contrib** [comment]
@AndreMiras I've just pushed a commit with the flower converted. Can you check that  did it fine? I would like to be sure that I followed the process correctly before doing the same for contextemenu.
Also can you add it to coveralls as requested in the migration process? I don't have any account there (and not really willing to make one). Thanks!

Last but not least: who can upload this on PyPI? I guess a common kivy account should be used, just in case somebody else needs to maintain it in the future.

**Comment by AndreMiras** [comment]
Nice @goffi-contrib thanks for that.
I've never played with modernmenu, but it looks good to me. I've only commented a minor typo introduced in the readme https://github.com/kivy-garden/modernmenu/commit/a09f4c2efec84aa9126ae872e2c87c95822f8d70#r36316351
I've fixed the build, it needed to have coveralls.io enabled for the repo, build is green now.
As for PyPI we don't have a common kivy account unfortunately. What we do is to create collaborators. I can look into it. I guess whoever publish the package should add at least @tshirtman (https://pypi.org/user/tshirtman/) as a collaborator as he made the initial commit it seems.

**Comment by AndreMiras** [comment]
I've published to https://pypi.org/project/kivy-garden.modernmenu/ and added both of you to the collaborators.
I think we can close this issue, eventually update the README.md of this project to redirect to the new one and archive the project.

**Comment by goffi-contrib** [comment]
@AndreMiras great, thanks a lot. I've fixed the typo in the readme. I'll do the same for contextmenu now, and I'm closing this ticket.

**Comment by AndreMiras** [comment]
All good thanks I'm archiving the repo
